### ISSUE TITLE
Enhancement: Support for own Domains/Subdomains

### ISSUE THREAD

**Issue by Kippenhof** [unofficial-skills/alpha-video#24]
Hey There,

As you know, i have the Docker Container running on my Unraid-Host. Because i allready have an Working Domain with an Subdomain-Wildcard-Cert  it would be nice if i just could pass the port through my nginx reverse-proxy and use an Subdomain instead of local.lt. (maybe an env-variable to disable local.lt)

**Comment by andrewstech** [comment]
Yes this would be good

**Comment by andrewstech** [comment]
HI this is now been added. If the variable localtunnel = false then local tunnel will be disabled. Otherwise if the variable is not set then docker will default to true.
