### ISSUE TITLE
Song identified correctly but not played

### ISSUE THREAD

**Issue by MoerkyMark** [unofficial-skills/alpha-video#28]
I have the issue that the song is correctly identified and it says "playing...." but actually nothing is played. Using an Amazon echo dot.

**Comment by andrewstech** [comment]
HI are you using docker for your install and what kind of system are you using for hosting the skill?

**Comment by MoerkyMark** [comment]
I'm using a local docker container on a linux based system (basically a QNAP NAS).

**Comment by andrewstech** [comment]
Not sure whats causing this issue. Does it do this for all videos?
