### ISSUE TITLE
template not found in log-entry

### ISSUE THREAD

**Issue by MoerkyMark** [unofficial-skills/alpha-video#29]
my docker.log entry says: your url is: https://XXX.loca.lt                                                                                                    
No localized template found for locale 'de-DE' and template 'card_title', falling back to default.

**Comment by andrewstech** [comment]
Hi the template its referring to is the 'card_title'. All this does is display the project name (Alpha Video) at the top of devices that have a screen.  Due to there being no translation of the project name it defaults back to English. The rest of the skill will skill be in your desired language.
