### ISSUE TITLE
luca.lt subdomain already taken when container restarted

### ISSUE THREAD

**Issue by MoerkyMark** [unofficial-skills/alpha-video#30]
I had the issue that with a restart of my docker container the subdomain was already taken by the previous run and therefore a random one was taken. Is there a way where you can delete such an instance. I had to choose another one.

**Comment by andrewstech** [comment]
This is an issue with localtunnel. I suggest opening an issue with them https://github.com/localtunnel/localtunnel

**Comment by andrewstech** [comment]
Sorry I couldn't be anymore helpful with this issue
