### ISSUE TITLE
Docker Stopps Auto-Build Support

### ISSUE THREAD

**Issue by Kippenhof** [unofficial-skills/alpha-video#73]
Docker will stop the support of Docker Auto-Builds on Free accs due to mining abuse. 
![Screenshot_2021-07-20-00-06-23-345_com.google.android.gm.jpg](https://user-images.githubusercontent.com/54744977/126274562-562d0f1f-fce0-43b6-b244-2dcbdecc5638.jpg)

Maybe we can find a free solution besides the manual build

**Comment by andrewstech** [comment]
I don't think our project will be effected as we use github actions to build the project then upload to docker.

**Comment by andrewstech** [comment]
Just checked auto builds we're disabled anyway.

**Comment by Kippenhof** [comment]
Oh, okay. Ill close it
