### ISSUE TITLE
An exception occurred while dispatching the request to the skill.

### ISSUE THREAD

**Issue by thefantas** [unofficial-skills/alpha-video#80]
"request": {
    "type": "SessionEndedRequest",
    "requestId": "amzn1.echo-api.request.252da626-0735-479b-8d21-0b9b4111db37",
    "timestamp": "2021-07-23T16:57:52Z",
    "locale": "es-ES",
    "reason": "ERROR",
    "error": {
      "type": "INVALID_RESPONSE",
      "message": "An exception occurred while dispatching the request to the skill."
    }
  }

**Comment by andrewstech** [comment]
Hi 👋. I  can see that it was an invalid response. However this could mean numerous different things. Here are some things I want you to check.
1. The Endpoint url starts with https:// and ends with /api 
2. If using a self hosted version then visit your Endpoint in browser if you see a page then good if not then that's where the issue lives.
3. Make sure under the interface tab of the alexa development console that both audio and video are enabled.

Hopefully one of these will sove your problem.
